/**
 * Dev sample — 3 scatters + 8 free spins (~16.00×).
 * Generated by scripts/build-sample-feature-book.mjs — do not hand-edit.
 */
export const SAMPLE_FEATURE_BOOK = {
  "id": 9001,
  "payoutMultiplier": 1600,
  "events": [
    {
      "index": 0,
      "type": "gameReveal",
      "board": [
        [
          "CH",
          "LM",
          "OR",
          "GR",
          "SC"
        ],
        [
          "OR",
          "GR",
          "LM",
          "CH",
          "S7"
        ],
        [
          "LM",
          "OR",
          "SC",
          "DM",
          "CH"
        ],
        [
          "GR",
          "CH",
          "LM",
          "OR",
          "CR"
        ],
        [
          "SC",
          "OR",
          "CH",
          "LM",
          "GR"
        ]
      ],
      "multiplier": 0
    },
    {
      "index": 1,
      "type": "enterBonus",
      "reason": "freeSpins",
      "total": 8,
      "scatters": 3
    },
    {
      "index": 2,
      "type": "updateFreeSpin",
      "current": 1,
      "total": 8
    },
    {
      "index": 3,
      "type": "gameReveal",
      "board": [
        [
          "DM",
          "GR",
          "S7",
          "OR",
          "GR"
        ],
        [
          "LM",
          "DM",
          "CR",
          "GR",
          "WD"
        ],
        [
          "OR",
          "LM",
          "OR",
          "S7",
          "LM"
        ],
        [
          "LM",
          "WD",
          "OR",
          "LM",
          "OR"
        ],
        [
          "CH",
          "OR",
          "GR",
          "WD",
          "WD"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 1
    },
    {
      "index": 4,
      "type": "updateFreeSpin",
      "current": 2,
      "total": 8
    },
    {
      "index": 5,
      "type": "gameReveal",
      "board": [
        [
          "WD",
          "GR",
          "LM",
          "LM",
          "CR"
        ],
        [
          "CR",
          "LM",
          "DM",
          "CR",
          "LM"
        ],
        [
          "DM",
          "S7",
          "S7",
          "CR",
          "ST"
        ],
        [
          "S7",
          "WD",
          "CR",
          "ST",
          "S7"
        ],
        [
          "WD",
          "ST",
          "GR",
          "CR",
          "WD"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 2
    },
    {
      "index": 6,
      "type": "clusterWin",
      "cascade": 1,
      "cascadeMultiplier": 1,
      "clusters": [
        {
          "symbol": "S7",
          "cells": [
            [
              2,
              1
            ],
            [
              3,
              1
            ],
            [
              3,
              0
            ],
            [
              4,
              0
            ],
            [
              2,
              2
            ]
          ],
          "size": 5,
          "baseMultiplier": 5
        }
      ],
      "stepMultiplier": 5,
      "removed": [
        [
          2,
          1
        ],
        [
          3,
          1
        ],
        [
          3,
          0
        ],
        [
          4,
          0
        ],
        [
          2,
          2
        ]
      ],
      "freeSpin": 2
    },
    {
      "index": 7,
      "type": "tumble",
      "board": [
        [
          "WD",
          "GR",
          "LM",
          "LM",
          "CR"
        ],
        [
          "CR",
          "LM",
          "DM",
          "CR",
          "LM"
        ],
        [
          "LM",
          "GR",
          "DM",
          "CR",
          "ST"
        ],
        [
          "OR",
          "S7",
          "CR",
          "ST",
          "S7"
        ],
        [
          "ST",
          "ST",
          "GR",
          "CR",
          "WD"
        ]
      ],
      "fills": [
        {
          "col": 2,
          "row": 0,
          "symbol": "LM"
        },
        {
          "col": 2,
          "row": 1,
          "symbol": "GR"
        },
        {
          "col": 3,
          "row": 0,
          "symbol": "OR"
        },
        {
          "col": 3,
          "row": 1,
          "symbol": "S7"
        },
        {
          "col": 4,
          "row": 0,
          "symbol": "ST"
        }
      ],
      "freeSpin": 2
    },
    {
      "index": 8,
      "type": "updateFreeSpin",
      "current": 3,
      "total": 8
    },
    {
      "index": 9,
      "type": "gameReveal",
      "board": [
        [
          "GR",
          "WD",
          "CH",
          "LM",
          "DM"
        ],
        [
          "DM",
          "OR",
          "WD",
          "CH",
          "ST"
        ],
        [
          "ST",
          "S7",
          "S7",
          "GR",
          "GR"
        ],
        [
          "LM",
          "WD",
          "ST",
          "CH",
          "WD"
        ],
        [
          "WD",
          "S7",
          "CR",
          "LM",
          "CR"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 3
    },
    {
      "index": 10,
      "type": "clusterWin",
      "cascade": 1,
      "cascadeMultiplier": 1,
      "clusters": [
        {
          "symbol": "S7",
          "cells": [
            [
              2,
              1
            ],
            [
              3,
              1
            ],
            [
              4,
              1
            ],
            [
              4,
              0
            ],
            [
              2,
              2
            ],
            [
              1,
              2
            ]
          ],
          "size": 6,
          "baseMultiplier": 6
        }
      ],
      "stepMultiplier": 6,
      "removed": [
        [
          2,
          1
        ],
        [
          3,
          1
        ],
        [
          4,
          1
        ],
        [
          4,
          0
        ],
        [
          2,
          2
        ],
        [
          1,
          2
        ]
      ],
      "freeSpin": 3
    },
    {
      "index": 11,
      "type": "tumble",
      "board": [
        [
          "GR",
          "WD",
          "CH",
          "LM",
          "DM"
        ],
        [
          "S7",
          "DM",
          "OR",
          "CH",
          "ST"
        ],
        [
          "CR",
          "DM",
          "ST",
          "GR",
          "GR"
        ],
        [
          "CH",
          "LM",
          "ST",
          "CH",
          "WD"
        ],
        [
          "CR",
          "ST",
          "CR",
          "LM",
          "CR"
        ]
      ],
      "fills": [
        {
          "col": 1,
          "row": 0,
          "symbol": "S7"
        },
        {
          "col": 2,
          "row": 0,
          "symbol": "CR"
        },
        {
          "col": 2,
          "row": 1,
          "symbol": "DM"
        },
        {
          "col": 3,
          "row": 0,
          "symbol": "CH"
        },
        {
          "col": 4,
          "row": 0,
          "symbol": "CR"
        },
        {
          "col": 4,
          "row": 1,
          "symbol": "ST"
        }
      ],
      "freeSpin": 3
    },
    {
      "index": 12,
      "type": "updateFreeSpin",
      "current": 4,
      "total": 8
    },
    {
      "index": 13,
      "type": "gameReveal",
      "board": [
        [
          "CR",
          "CH",
          "WD",
          "ST",
          "GR"
        ],
        [
          "ST",
          "DM",
          "LM",
          "OR",
          "LM"
        ],
        [
          "DM",
          "OR",
          "OR",
          "ST",
          "CR"
        ],
        [
          "LM",
          "CR",
          "CR",
          "CR",
          "CH"
        ],
        [
          "CR",
          "S7",
          "LM",
          "DM",
          "DM"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 4
    },
    {
      "index": 14,
      "type": "updateFreeSpin",
      "current": 5,
      "total": 8
    },
    {
      "index": 15,
      "type": "gameReveal",
      "board": [
        [
          "ST",
          "OR",
          "CR",
          "ST",
          "DM"
        ],
        [
          "S7",
          "ST",
          "S7",
          "DM",
          "WD"
        ],
        [
          "OR",
          "CR",
          "CR",
          "LM",
          "WD"
        ],
        [
          "OR",
          "CH",
          "OR",
          "CH",
          "GR"
        ],
        [
          "CR",
          "DM",
          "GR",
          "CH",
          "S7"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 5
    },
    {
      "index": 16,
      "type": "updateFreeSpin",
      "current": 6,
      "total": 8
    },
    {
      "index": 17,
      "type": "gameReveal",
      "board": [
        [
          "ST",
          "DM",
          "GR",
          "GR",
          "S7"
        ],
        [
          "ST",
          "S7",
          "CR",
          "CH",
          "WD"
        ],
        [
          "ST",
          "DM",
          "LM",
          "CH",
          "ST"
        ],
        [
          "CR",
          "CR",
          "DM",
          "LM",
          "WD"
        ],
        [
          "CH",
          "LM",
          "GR",
          "WD",
          "GR"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 6
    },
    {
      "index": 18,
      "type": "updateFreeSpin",
      "current": 7,
      "total": 8
    },
    {
      "index": 19,
      "type": "gameReveal",
      "board": [
        [
          "DM",
          "LM",
          "ST",
          "DM",
          "DM"
        ],
        [
          "CH",
          "CH",
          "CR",
          "WD",
          "LM"
        ],
        [
          "CR",
          "CR",
          "GR",
          "DM",
          "DM"
        ],
        [
          "CR",
          "ST",
          "DM",
          "LM",
          "LM"
        ],
        [
          "S7",
          "OR",
          "S7",
          "CR",
          "DM"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 7
    },
    {
      "index": 20,
      "type": "clusterWin",
      "cascade": 1,
      "cascadeMultiplier": 1,
      "clusters": [
        {
          "symbol": "DM",
          "cells": [
            [
              0,
              3
            ],
            [
              1,
              3
            ],
            [
              2,
              3
            ],
            [
              2,
              4
            ],
            [
              0,
              4
            ]
          ],
          "size": 5,
          "baseMultiplier": 5
        }
      ],
      "stepMultiplier": 5,
      "removed": [
        [
          0,
          3
        ],
        [
          1,
          3
        ],
        [
          2,
          3
        ],
        [
          2,
          4
        ],
        [
          0,
          4
        ]
      ],
      "freeSpin": 7
    },
    {
      "index": 21,
      "type": "tumble",
      "board": [
        [
          "OR",
          "OR",
          "DM",
          "LM",
          "ST"
        ],
        [
          "S7",
          "CH",
          "CH",
          "CR",
          "LM"
        ],
        [
          "ST",
          "S7",
          "CR",
          "CR",
          "GR"
        ],
        [
          "CR",
          "ST",
          "DM",
          "LM",
          "LM"
        ],
        [
          "S7",
          "OR",
          "S7",
          "CR",
          "DM"
        ]
      ],
      "fills": [
        {
          "col": 0,
          "row": 0,
          "symbol": "OR"
        },
        {
          "col": 0,
          "row": 1,
          "symbol": "OR"
        },
        {
          "col": 1,
          "row": 0,
          "symbol": "S7"
        },
        {
          "col": 2,
          "row": 0,
          "symbol": "ST"
        },
        {
          "col": 2,
          "row": 1,
          "symbol": "S7"
        }
      ],
      "freeSpin": 7
    },
    {
      "index": 22,
      "type": "updateFreeSpin",
      "current": 8,
      "total": 8
    },
    {
      "index": 23,
      "type": "gameReveal",
      "board": [
        [
          "OR",
          "CH",
          "WD",
          "LM",
          "GR"
        ],
        [
          "WD",
          "GR",
          "ST",
          "CH",
          "CR"
        ],
        [
          "ST",
          "CH",
          "S7",
          "OR",
          "CH"
        ],
        [
          "LM",
          "S7",
          "OR",
          "CR",
          "WD"
        ],
        [
          "S7",
          "ST",
          "ST",
          "ST",
          "LM"
        ]
      ],
      "multiplier": 0,
      "freeSpin": 8
    },
    {
      "index": 24,
      "type": "freeSpinEnd",
      "amount": 1600,
      "totalMultiplier": 16
    },
    {
      "index": 25,
      "type": "setTotalWin",
      "amount": 1600
    },
    {
      "index": 26,
      "type": "finalWin",
      "amount": 1600
    }
  ],
  "totalMultiplier": 16,
  "featureMultiplier": 16,
  "scatterCount": 3
};
